# https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml

# title: Nguyen Anh Minh MAI
logo: https://maiminh1996.github.io/minh.png
# description: Ph.D student in Computer Science
theme: jekyll-theme-minimal

# --- Footer social media links --- # not work
social-network-links:
  email: "someone@example.com"
  facebook: deanattali
  github: daattali
  twitter: daattali
  patreon: DeanAttali
  youtube: c/daattali

date_format: "%B %-d, %Y"

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
